# Generated by Django 6.0.6 on 2026-07-07 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(db_column='RUT', max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('talla', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMayor',
            fields=[
                ('id_material', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('especialidad', models.CharField(db_column='Especialidad', max_length=100)),
                ('marca', models.CharField(db_column='Marca', max_length=100)),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('anio', models.IntegerField(db_column='Anio')),
                ('estado', models.CharField(db_column='Estado', max_length=50)),
                ('latitud', models.DecimalField(blank=True, db_column='Latitud', decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, db_column='Longitud', decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('rut', models.OneToOneField(db_column='RUT', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.persona')),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bombero',
            fields=[
                ('rut', models.OneToOneField(db_column='RUT', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.persona')),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('rango', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
                ('id_actividad', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, to='api.actividad')),
                ('rut', models.ForeignKey(db_column='RUT', on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('rut', models.ForeignKey(db_column='RUT', on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id_emergencia', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(db_column='Clave', max_length=50)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150)),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('sector', models.CharField(db_column='Sector', max_length=100)),
                ('hora', models.TimeField(blank=True, db_column='Hora', null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('id_actividad', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, to='api.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.AutoField(primary_key=True, serialize=False)),
                ('hora_despacho', models.TimeField(blank=True, null=True)),
                ('hora_regreso', models.TimeField(blank=True, null=True)),
                ('id_emergencia', models.ForeignKey(db_column='id_emergencia', on_delete=django.db.models.deletion.CASCADE, to='api.emergencia')),
                ('id_material_mayor', models.ForeignKey(db_column='id_material_mayor', on_delete=django.db.models.deletion.CASCADE, to='api.materialmayor')),
            ],
        ),
        migrations.CreateModel(
            name='Tripulacion',
            fields=[
                ('id_tripulacion', models.AutoField(primary_key=True, serialize=False)),
                ('funcion', models.CharField(max_length=100)),
                ('id_despacho', models.ForeignKey(db_column='id_despacho', on_delete=django.db.models.deletion.CASCADE, to='api.despacho')),
                ('rut', models.ForeignKey(db_column='RUT', on_delete=django.db.models.deletion.CASCADE, to='api.bombero')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoAsignado',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('codigo', models.ForeignKey(db_column='Codigo', on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
                ('rut', models.ForeignKey(db_column='RUT', on_delete=django.db.models.deletion.CASCADE, to='api.bombero')),
            ],
        ),
    ]
