# Generated by Django 6.0.6 on 2026-07-07 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipoAsignado',
            new_name='Equipo_Asignado',
        ),
    ]
