# Generated by Django 6.0.6 on 2026-07-08 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(db_column='RUT', max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('talla', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('rut', models.OneToOneField(db_column='RUT', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Administracion.persona')),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bombero',
            fields=[
                ('rut', models.OneToOneField(db_column='RUT', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Administracion.persona')),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('rango', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('rut', models.ForeignKey(db_column='RUT', on_delete=django.db.models.deletion.CASCADE, to='Administracion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo_Asignado',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('codigo', models.ForeignKey(db_column='Codigo', on_delete=django.db.models.deletion.CASCADE, to='Administracion.equipo')),
                ('rut', models.ForeignKey(db_column='RUT', on_delete=django.db.models.deletion.CASCADE, to='Administracion.bombero')),
            ],
        ),
    ]
