# Generated by Django 6.0.6 on 2026-07-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='contraseña',
            field=models.CharField(default=123, max_length=32),
            preserve_default=False,
        ),
    ]
