# Generated by Django 6.0.6 on 2026-07-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0002_persona_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='contraseña',
            field=models.CharField(max_length=255),
        ),
    ]
