# Generated by Django 6.0.7 on 2026-07-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0003_alter_persona_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bombero',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Encuesta_Guardia',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(db_column='Creado_Por', on_delete=django.db.models.deletion.CASCADE, to='Administracion.bombero')),
            ],
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id_guardia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('DIA', 'Día'), ('NOCHE', 'Noche')], max_length=10)),
                ('numero', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cupos', models.IntegerField(default=4)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('COMPLETA', 'Completa'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('encuesta', models.ForeignKey(db_column='Id_Encuesta', on_delete=django.db.models.deletion.CASCADE, to='Administracion.encuesta_guardia')),
                ('maquinista', models.ForeignKey(blank=True, db_column='Maquinista', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinista_guardias', to='Administracion.bombero')),
                ('oficial_a_cargo', models.ForeignKey(blank=True, db_column='Oficial_A_Cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficial_guardias', to='Administracion.bombero')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion_Guardia',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('bombero', models.ForeignKey(db_column='RUT', on_delete=django.db.models.deletion.CASCADE, to='Administracion.bombero')),
                ('guardia', models.ForeignKey(db_column='Id_Guardia', on_delete=django.db.models.deletion.CASCADE, to='Administracion.guardia')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia_Guardia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado')], default='PRESENTE', max_length=20)),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('inscripcion', models.OneToOneField(db_column='Id_Inscripcion', on_delete=django.db.models.deletion.CASCADE, to='Administracion.inscripcion_guardia')),
            ],
        ),
        migrations.CreateModel(
            name='Instruccion_Guardia',
            fields=[
                ('id_instruccion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('encuesta', models.ForeignKey(db_column='Id_Encuesta', on_delete=django.db.models.deletion.CASCADE, to='Administracion.encuesta_guardia')),
            ],
        ),
        migrations.CreateModel(
            name='RecuperacionContraseña',
            fields=[
                ('id_recuperacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(db_column='RUT', on_delete=django.db.models.deletion.CASCADE, to='Administracion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea_Guardia',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('guardia', models.ForeignKey(db_column='Id_Guardia', on_delete=django.db.models.deletion.CASCADE, to='Administracion.guardia')),
            ],
        ),
    ]
