# Generated by Django 6.0.6 on 2026-07-08 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMayor',
            fields=[
                ('id_material', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('especialidad', models.CharField(db_column='Especialidad', max_length=100)),
                ('marca', models.CharField(db_column='Marca', max_length=100)),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('anio', models.IntegerField(db_column='Anio')),
                ('estado', models.CharField(db_column='Estado', max_length=50)),
                ('latitud', models.DecimalField(blank=True, db_column='Latitud', decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, db_column='Longitud', decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
                ('id_actividad', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, to='Operacion.actividad')),
                ('rut', models.ForeignKey(db_column='RUT', on_delete=django.db.models.deletion.CASCADE, to='Administracion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id_emergencia', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(db_column='Clave', max_length=50)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150)),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('sector', models.CharField(db_column='Sector', max_length=100)),
                ('hora', models.TimeField(blank=True, db_column='Hora', null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('id_actividad', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, to='Operacion.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.AutoField(primary_key=True, serialize=False)),
                ('hora_despacho', models.TimeField(blank=True, null=True)),
                ('hora_regreso', models.TimeField(blank=True, null=True)),
                ('id_emergencia', models.ForeignKey(db_column='id_emergencia', on_delete=django.db.models.deletion.CASCADE, to='Operacion.emergencia')),
                ('id_material_mayor', models.ForeignKey(db_column='id_material_mayor', on_delete=django.db.models.deletion.CASCADE, to='Operacion.materialmayor')),
            ],
        ),
        migrations.CreateModel(
            name='Tripulacion',
            fields=[
                ('id_tripulacion', models.AutoField(primary_key=True, serialize=False)),
                ('funcion', models.CharField(max_length=100)),
                ('id_despacho', models.ForeignKey(db_column='id_despacho', on_delete=django.db.models.deletion.CASCADE, to='Operacion.despacho')),
                ('rut', models.ForeignKey(db_column='RUT', on_delete=django.db.models.deletion.CASCADE, to='Administracion.bombero')),
            ],
        ),
    ]
