# Generated by Django 6.0.6 on 2026-10-04 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0003_alter_persona_contraseña'),
        ('Operacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha', models.DateTimeField()),
                ('cupos', models.IntegerField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierta'), ('CERRADO', 'Cerrada')], default='ABIERTO', max_length=20)),
                ('oficial_a_cargo', models.ForeignKey(db_column='RUT_Oficial', on_delete=django.db.models.deletion.CASCADE, to='Administracion.bombero')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion_Curso',
            fields=[
                ('id_inscripcion_curso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('bombero', models.ForeignKey(db_column='RUT_Bombero', on_delete=django.db.models.deletion.CASCADE, to='Administracion.bombero')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='Operacion.curso')),
            ],
            options={
                'unique_together': {('curso', 'bombero')},
            },
        ),
    ]
